name: Lighthouse Audit

on:
  push:
    branches:
      - main # Adjust this to the branch you want to monitor

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Install node
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run Lighthouse Audit
        run: lighthouse http://localhost:5173 --output json --output-path lighthouse-report.json

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lighthouse-report.json
